apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-read-service
  namespace: tokentrackr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-read-service
  template:
    metadata:
      labels:
        app: crypto-read-service
    spec:
      containers:
      - name: crypto-read-service
        image: ${IMAGE_NAME}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq-release
        - name: REDIS_HOST
          value: redis-release-master
        - name: REDIS_PORT
          value: "6379"

---

apiVersion: v1
kind: Service
metadata:
  name: crypto-read-service
  namespace: tokentrackr
  annotations:
    prometheus.io/scrape: "true"     # Essential - enables scraping
    prometheus.io/port: "8080"       # Where metrics are exposed
    prometheus.io/path: "/actuator/prometheus"  # Metrics endpoint
spec:
  selector:
    app: crypto-read-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
