name: CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Make Maven Wrapper executable
        run: chmod +x ./mvnw

      - name: Build and run tests (skip OWASP Dependency-Check)
        run: ./mvnw clean verify -Ddependency-check.skip=true

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw sonar:sonar \
          -Dsonar.organization=tokentrackr \
          -Dsonar.projectKey=TokenTrackr_crypto-read-service \
          -Dsonar.login=$SONAR_TOKEN
